### ISSUE TITLE
4.2.2-stable release of the patched godot fork seems to have export templates for godot 4.3

### ISSUE THREAD

**Issue by bypell** [stechyo/godot-steam-audio#58]
**Are you using the provided fork of Godot?**
yes

**Godot-steam-audio version**
0.2.0

**Steam-Audio version**
4.5.3

**Operating System**
Windows 11

**Describe the bug**
getting these errors when trying to run an exported project using the export templates available in the release section of the godot fork.
![image](https://github.com/stechyo/godot-steam-audio/assets/35241316/ac984bed-63f5-4103-82a6-1a048a9d04ff)
(since the export templates were added a month after the editor executables, you probably forgot to switch back to 4.2.2 and build them with that version?)

**To Reproduce**

**Expected behavior**
no errors/crash

**Example project, code snippet, or screenshots**

**Additional context**

**Comment by stechyo** [comment]
Hi, thanks for the heads-up! As you guessed I built the export templates with the wrong branch, didn't notice it since my project doesn't have Jolt or anything that would break on 4.3. I rebuilt all of the templates and replaced them in the [release](https://github.com/stechyo/godot/releases/tag/4.2.2-stable-steam-audio).
