### ISSUE TITLE
Error at runtime in example scene

### ISSUE THREAD

**Issue by jacob-herrera** [stechyo/godot-steam-audio#7]
```
E 0:00:00:0026   set_object_extension_instance: Cannot get class 'SteamAudioServer'.
  <C++ Error>    Parameter "ti" is null.
  <C++ Source>   core/object/class_db.cpp:392 @ set_object_extension_instance()
```

Though, all the audio seems to be working still.
On Windows with Steam Audio v4.5.0 and the latest Godot 4.2-audio-stream-funcs.

Files in `/bin`

```
GPUUtilities.dll
libgodot-steam-audio.gdextension
libgodot-steam-audio.windows.template_debug.x86_64.dll
phonon.dll
phonon.lib
TrueAudioNext.dll
```

**Comment by stechyo** [comment]
Hi, thanks for opening this. I should have opened it myself because I was already aware of it. This is probably something missing in the extension's class registration or intialization, but it doesn't affect the audio. I'll see if I can fix it eventually since it's annoying and not the greatest first impression.

**Comment by stechyo** [comment]
#11 resolves this error, I probably won't create a release just for it so it'll come bundled with any next features. Thanks for opening this (and if you want a chuckle, do check the PR).
